name: Publish Package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish-aar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Linting
        run: ./gradlew ciLint
      - name: Unit Tests
        run: ./gradlew checkTestCoverage
      - name: Build Android aar
        run: ./gradlew tyro-pay-android:assemble
      - name: Publish aar to GitHub Packages
        run: ./gradlew publish
        env:
          GH_PACKAGE_USER: ${{github.actor}}
          GH_PACKAGE_TOKEN: ${{secrets.GITHUB_TOKEN}}

     
