name: Release CI
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Select release type'
        required: true
        default: 'draft'
        type: choice
        options: 
          - draft
          - prerelease
          - release

jobs:
  git-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name : Retrieve Version Name
        run: echo "VERSION=$(./gradlew -q printVersionName -Pprefix=v)" >> $GITHUB_OUTPUT
        id: android_version
      - name: Print Version Name
        run: echo "release version ${{steps.android_version.outputs.VERSION}}"
      - name: Create GitHub Tag and Release
        uses: ncipollo/release-action@v1
        with:
          ${{ inputs.release-type }}: true
          generateReleaseNotes: true
          tag: "${{steps.android_version.outputs.VERSION}}"
          commit: "master"
  publish-aar:
    needs: git-release
    if: ${{inputs.release-type != 'draft'}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Linting
        run: ./gradlew ciLint
      - name: Unit Tests
        run: ./gradlew checkTestCoverage
      - name: Build Android aar
        run: ./gradlew tyro-pay-android:assemble
      - name: Publish aar to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_PACKAGES_USER: ${{github.actor}}
          GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}


  